# Generated by Django 3.1.1 on 2021-05-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210529_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='novelchapter',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20),
        ),
    ]
