# Generated by Django 3.1.1 on 2021-05-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210529_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovelChapter',
            new_name='Chapter',
        ),
    ]
