# Generated by Django 3.1.1 on 2021-05-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210529_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='excerpt',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='excerpt',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='excerpt',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
