# Generated by Django 3.1.1 on 2021-05-29 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210529_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('poetry', 'Poetry'), ('fiction', 'Fiction'), ('nonfition', 'Nonfiction')], default='Blog', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('poetry', 'Poetry'), ('fiction', 'Fiction'), ('nonfition', 'Nonfiction')], default='Blog', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='Draft', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='under',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shortstory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
        migrations.DeleteModel(
            name='ShortStory',
        ),
    ]
