# Generated by Django 3.1.1 on 2021-05-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210529_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.book'),
        ),
    ]
